name:                worldhaskbook
version:             0.1.0.0
github:              "smithhmark/worldhaskbook"
license:             BSD3
author:              "Mark Smith"
maintainer:          "smith.h.mark@gmail.com"
copyright:           "value"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smithhmark/worldhaskbook#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers
  - HandsomeSoup
  - hxt
  - time

executables:
  worldhaskbook-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - worldhaskbook

tests:
  worldhaskbook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - worldhaskbook
    - hspec
