module Locations where

locations = [
  ("World","xx"),
  ("Afghanistan","af"),
  ("Akrotiri","ax"),
  ("Albania","al"),
  ("Algeria","ag"),
  ("American Samoa","aq"),
  ("Andorra","an"),
  ("Angola","ao"),
  ("Anguilla","av"),
  ("Antarctica","ay"),
  ("Antigua and Barbuda","ac"),
  ("Arctic Ocean","xq"),
  ("Argentina","ar"),
  ("Armenia","am"),
  ("Aruba","aa"),
  ("Ashmore and Cartier Islands","at"),
  ("Atlantic Ocean","zh"),
  ("Australia","as"),
  ("Austria","au"),
  ("Azerbaijan","aj"),
  ("Bahamas, The","bf"),
  ("Bahrain","ba"),
  ("Baker Island","um"),
  ("Bangladesh","bg"),
  ("Barbados","bb"),
  ("Belarus","bo"),
  ("Belgium","be"),
  ("Belize","bh"),
  ("Benin","bn"),
  ("Bermuda","bd"),
  ("Bhutan","bt"),
  ("Bolivia","bl"),
  ("Bosnia and Herzegovina","bk"),
  ("Botswana","bc"),
  ("Bouvet Island","bv"),
  ("Brazil","br"),
  ("British Indian Ocean Territory","io"),
  ("British Virgin Islands","vi"),
  ("Brunei","bx"),
  ("Bulgaria","bu"),
  ("Burkina Faso","uv"),
  ("Burma","bm"),
  ("Burundi","by"),
  ("Cabo Verde","cv"),
  ("Cambodia","cb"),
  ("Cameroon","cm"),
  ("Canada","ca"),
  ("Cayman Islands","cj"),
  ("Central African Republic","ct"),
  ("Chad","cd"),
  ("Chile","ci"),
  ("China","ch"),
  ("Christmas Island","kt"),
  ("Clipperton Island","ip"),
  ("Cocos (Keeling) Islands","ck"),
  ("Colombia","co"),
  ("Comoros","cn"),
  ("Congo, Democratic Republic of the","cg"),
  ("Congo, Republic of the","cf"),
  ("Cook Islands","cw"),
  ("Coral Sea Islands","cr"),
  ("Costa Rica","cs"),
  ("Cote d'Ivoire","iv"),
  ("Croatia","hr"),
  ("Cuba","cu"),
  ("Curacao","uc"),
  ("Cyprus","cy"),
  ("Czechia","ez"),
  ("Denmark","da"),
  ("Dhekelia","dx"),
  ("Djibouti","dj"),
  ("Dominica","do"),
  ("Dominican Republic","dr"),
  ("Ecuador","ec"),
  ("Egypt","eg"),
  ("El Salvador","es"),
  ("Equatorial Guinea","ek"),
  ("Eritrea","er"),
  ("Estonia","en"),
  ("Eswatini","wz"),
  ("Ethiopia","et"),
  ("Falkland Islands (Islas Malvinas)","fk"),
  ("Faroe Islands","fo"),
  ("Fiji","fj"),
  ("Finland","fi"),
  ("France","fr"),
  ("French Polynesia","fp"),
  ("French Southern and Antarctic Lands","fs"),
  ("Gabon","gb"),
  ("Gambia, The","ga"),
  ("Gaza Strip","gz"),
  ("Georgia","gg"),
  ("Germany","gm"),
  ("Ghana","gh"),
  ("Gibraltar","gi"),
  ("Greece","gr"),
  ("Greenland","gl"),
  ("Grenada","gj"),
  ("Guam","gq"),
  ("Guatemala","gt"),
  ("Guernsey","gk"),
  ("Guinea","gv"),
  ("Guinea-Bissau","pu"),
  ("Guyana","gy"),
  ("Haiti","ha"),
  ("Heard Island and McDonald Islands","hm"),
  ("Holy See (Vatican City)","vt"),
  ("Honduras","ho"),
  ("Hong Kong","hk"),
  ("Howland Island","um"),
  ("Hungary","hu"),
  ("Iceland","ic"),
  ("India","in"),
  ("Indian Ocean","xo"),
  ("Indonesia","id"),
  ("Iran","ir"),
  ("Iraq","iz"),
  ("Ireland","ei"),
  ("Isle of Man","im"),
  ("Israel","is"),
  ("Italy","it"),
  ("Jamaica","jm"),
  ("Jan Mayen","jn"),
  ("Japan","ja"),
  ("Jarvis Island","um"),
  ("Jersey","je"),
  ("Johnston Atoll","um"),
  ("Jordan","jo"),
  ("Kazakhstan","kz"),
  ("Kenya","ke"),
  ("Kingman Reef","um"),
  ("Kiribati","kr"),
  ("Korea, North","kn"),
  ("Korea, South","ks"),
  ("Kosovo","kv"),
  ("Kuwait","ku"),
  ("Kyrgyzstan","kg"),
  ("Laos","la"),
  ("Latvia","lg"),
  ("Lebanon","le"),
  ("Lesotho","lt"),
  ("Liberia","li"),
  ("Libya","ly"),
  ("Liechtenstein","ls"),
  ("Lithuania","lh"),
  ("Luxembourg","lu"),
  ("Macau","mc"),
  ("Macedonia","mk"),
  ("Madagascar","ma"),
  ("Malawi","mi"),
  ("Malaysia","my"),
  ("Maldives","mv"),
  ("Mali","ml"),
  ("Malta","mt"),
  ("Marshall Islands","rm"),
  ("Mauritania","mr"),
  ("Mauritius","mp"),
  ("Mexico","mx"),
  ("Micronesia, Federated States of","fm"),
  ("Midway Islands","um"),
  ("Moldova","md"),
  ("Monaco","mn"),
  ("Mongolia","mg"),
  ("Montenegro","mj"),
  ("Montserrat","mh"),
  ("Morocco","mo"),
  ("Mozambique","mz"),
  ("Namibia","wa"),
  ("Nauru","nr"),
  ("Navassa Island","bq"),
  ("Nepal","np"),
  ("Netherlands","nl"),
  ("New Caledonia","nc"),
  ("New Zealand","nz"),
  ("Nicaragua","nu"),
  ("Niger","ng"),
  ("Nigeria","ni"),
  ("Niue","ne"),
  ("Norfolk Island","nf"),
  ("Northern Mariana Islands","cq"),
  ("Norway","no"),
  ("Oman","mu"),
  ("Pacific Ocean","zn"),
  ("Pakistan","pk"),
  ("Palau","ps"),
  ("Palmyra Atoll","um"),
  ("Panama","pm"),
  ("Papua New Guinea","pp"),
  ("Paracel Islands","pf"),
  ("Paraguay","pa"),
  ("Peru","pe"),
  ("Philippines","rp"),
  ("Pitcairn Islands","pc"),
  ("Poland","pl"),
  ("Portugal","po"),
  ("Puerto Rico","rq"),
  ("Qatar","qa"),
  ("Romania","ro"),
  ("Russia","rs"),
  ("Rwanda","rw"),
  ("Saint Barthelemy","tb"),
  ("Saint Helena, Ascension, and Tristan da Cunha","sh"),
  ("Saint Kitts and Nevis","sc"),
  ("Saint Lucia","st"),
  ("Saint Martin","rn"),
  ("Saint Pierre and Miquelon","sb"),
  ("Saint Vincent and the Grenadines","vc"),
  ("Samoa","ws"),
  ("San Marino","sm"),
  ("Sao Tome and Principe","tp"),
  ("Saudi Arabia","sa"),
  ("Senegal","sg"),
  ("Serbia","ri"),
  ("Seychelles","se"),
  ("Sierra Leone","sl"),
  ("Singapore","sn"),
  ("Sint Maarten","nn"),
  ("Slovakia","lo"),
  ("Slovenia","si"),
  ("Solomon Islands","bp"),
  ("Somalia","so"),
  ("South Africa","sf"),
  ("South Georgia and South Sandwich Islands","sx"),
  ("South Sudan","od"),
  ("Southern Ocean","oo"),
  ("Spain","sp"),
  ("Spratly Islands","pg"),
  ("Sri Lanka","ce"),
  ("Sudan","su"),
  ("Suriname","ns"),
  ("Svalbard","sv"),
  ("Sweden","sw"),
  ("Switzerland","sz"),
  ("Syria","sy"),
  ("Taiwan","tw"),
  ("Tajikistan","ti"),
  ("Tanzania","tz"),
  ("Thailand","th"),
  ("Timor-Leste","tt"),
  ("Togo","to"),
  ("Tokelau","tl"),
  ("Tonga","tn"),
  ("Trinidad and Tobago","td"),
  ("Tunisia","ts"),
  ("Turkey","tu"),
  ("Turkmenistan","tx"),
  ("Turks and Caicos Islands","tk"),
  ("Tuvalu","tv"),
  ("Uganda","ug"),
  ("Ukraine","up"),
  ("United Arab Emirates","ae"),
  ("United Kingdom","uk"),
  ("United States","us"),
  ("United States Pacific Island Wildlife Refuges","um"),
  ("Uruguay","uy"),
  ("Uzbekistan","uz"),
  ("Vanuatu","nh"),
  ("Venezuela","ve"),
  ("Vietnam","vm"),
  ("Virgin Islands","vq"),
  ("Wake Island","wq"),
  ("Wallis and Futuna","wf"),
  ("West Bank","we"),
  ("Western Sahara","wi"),
  ("Yemen","ym"),
  ("Zambia","za"),
  ("Zimbabwe","zi"),
  ("European Union","ee")
  ]
